# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notionctl < Formula
  desc "Declarative Notion database management. Define databases in YAML, sync to Notion."
  homepage "https://github.com/radityajay/notionctl"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/radityajay/notionctl/releases/download/v1.1.0/notionctl_1.1.0_darwin_amd64.tar.gz"
      sha256 "457d3ad99d0bf488b69d5d6cafb1b1643009473744ee5911cd61b2418c0e4be7"

      define_method(:install) do
        bin.install "notionctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/radityajay/notionctl/releases/download/v1.1.0/notionctl_1.1.0_darwin_arm64.tar.gz"
      sha256 "26042a6986620aad1da71124292f15eca95ddaa3c00d568a2ec6a4ab71d51c25"

      define_method(:install) do
        bin.install "notionctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/radityajay/notionctl/releases/download/v1.1.0/notionctl_1.1.0_linux_amd64.tar.gz"
      sha256 "149d71764b9c2a1dec7c74357447840cabd1e5c67362c52d68274b96a71dc9b9"
      define_method(:install) do
        bin.install "notionctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/radityajay/notionctl/releases/download/v1.1.0/notionctl_1.1.0_linux_arm64.tar.gz"
      sha256 "87ba27eccc245df2b4546a20a797f6e438cbee7582fe0e9b1297a6e1a54c3630"
      define_method(:install) do
        bin.install "notionctl"
      end
    end
  end

  test do
    system "#{bin}/notionctl", "version"
  end
end
