# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notionctl < Formula
  desc "Declarative Notion database management. Define databases in YAML, sync to Notion."
  homepage "https://github.com/radityajay/notionctl"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/radityajay/notionctl/releases/download/v1.3.1/notionctl_1.3.1_darwin_amd64.tar.gz"
      sha256 "52b30067120a56f12d2710c13efc43865d6bf7530934157e17b284038f5454aa"

      define_method(:install) do
        bin.install "notionctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/radityajay/notionctl/releases/download/v1.3.1/notionctl_1.3.1_darwin_arm64.tar.gz"
      sha256 "d419d0ae0252e0e4519b7883fdcf115e43cf6c65a3e20f74ef23233e17adf4dc"

      define_method(:install) do
        bin.install "notionctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/radityajay/notionctl/releases/download/v1.3.1/notionctl_1.3.1_linux_amd64.tar.gz"
      sha256 "e3f091377c737d5b7fe0acfcc291efc5be825fcc396a131c60e290201a1993d1"
      define_method(:install) do
        bin.install "notionctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/radityajay/notionctl/releases/download/v1.3.1/notionctl_1.3.1_linux_arm64.tar.gz"
      sha256 "6f7690ff7c4a0aebec9f31d81a6446648f2bae23b1ea892973f80339acd24f26"
      define_method(:install) do
        bin.install "notionctl"
      end
    end
  end

  test do
    system "#{bin}/notionctl", "version"
  end
end
